# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180521_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('depature', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passengers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='first_app.User')),
            ],
        ),
    ]
