# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_trip_travel_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='first_app.User'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(related_name='passengers', to='first_app.User'),
        ),
    ]
