# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20180529_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(related_name='travel_buddy', to='first_app.User'),
        ),
    ]
